# Generated by Django 4.0.5 on 2022-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_empregister_model_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleave_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from1', models.DateField()),
                ('to1', models.DateField()),
                ('day', models.CharField(choices=[('H', 'Half day'), ('F', 'Full day')], max_length=1)),
                ('reason', models.TextField()),
            ],
        ),
    ]
