# Generated by Django 4.0.5 on 2022-06-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_empleave_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleave_model',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.empregister_model'),
        ),
    ]
