# Generated by Django 4.0.5 on 2022-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_empleave_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleave_model',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
