# Generated by Django 4.0.5 on 2022-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_empleave_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleave_model',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
