# Generated by Django 4.0.5 on 2022-07-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_empleave_model_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
