# Generated by Django 4.0.5 on 2022-07-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_status_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status_model',
        ),
    ]
